### ISSUE TITLE
Call to GenesysCloudWebrtcSdk.destroy() never resolves

### ISSUE THREAD

**Issue by bdbvb** [MyPureCloud/genesys-cloud-webrtc-sdk#706] opened 2022-05-13 15:01 UTC
Using v7.2.3.

After receiving an inbound call and hanging up*, if I try to cleanup via client.destroy(), the resulting promise never resolves. (It works OK if a call was never received.)

The code is similar to this:
```
try {
    await client.destroy();
    // never gets to here
    console.log("here"); 
} catch (e: any) {
   // or here
   console.log(e);
}
```

Digging a little further, if I try to manually do what destroy does, it turns out to be the call to sessionManager.endSession() that never resolves.
```
try {
    const activeSessions = client.sessionManager.getAllJingleSessions();
    await Promise.all(activeSessions.map(s => client.sessionManager.endSession(s)));
    // never gets to here
    console.log("here"); 
    client.removeAllListeners();
    client.media.destroy();
    await client.disconnect();
} catch (e: any) {
   // or here
   console.log(e);
}
```

Any ideas why that promise would never resolve?

----
Additional Info:
- *hanging up not via this SDK but via the Genesys APIs
- Persistent Connection is ON

**Comment by djhouseknecht** [comment] 2022-05-13 15:32
Good catch. I'll have to dig into the root cause but the TLDR is because when using Persistent Connection, `client.sessionManager.endSession(s)` doesn't actually end the Webrtc Session. It only `PATCH`es the conversation via the API and responds to the conversation events. 

I'll open a ticket to look into the root cause because `sessionManger.endSession` _should_ still resolve whether or not we tear down the webrtc session. 

Here is a hacky little work around for now. But we will try to get this fixed in 7.2.4
``` js
try {
    const activeSessions = sdk.sessionManager.getAllJingleSessions();
    if (activeSessions.length === 1 && !sdk.isConcurrentSoftphoneSessionsEnabled()) {
        await sdk.sessionManager.forceTerminateSession(activeSessions[0].id)
    } else {
        await Promise.all(activeSessions.map(s => sdk.sessionManager.endSession(s)));
    }
    // you will get here now
    console.log("here"); 
    sdk.removeAllListeners();
    sdk.media.destroy();
    await sdk.disconnect();
} catch (e) {
   // and/or here
   console.log(e);
}
```

**Comment by bdbvb** [comment] 2022-05-13 21:37
Interestingly, it seems I still get the same behavior with the workaround; namely, activeSessions.length is 1 but isConcurrentSoftphoneSessionsEnabled() is true. I have persistent connection turned on, but how would I update the line appearance to 1?

**Comment by djhouseknecht** [comment] 2022-05-13 21:42
I'm sorry, @bdbvb, I was thinking LA == 1. You could use `sdk.isPersistentConnectionEnabled()` in your workaround check. I will update original response. 

Updating the Line Appearance to 1 is a station/phone configuration item. I don't think there is direct way to update that. Eventually, all stations will have LA == 1 but that migration hasn't started yet. The release of sdk v7 was to lay the ground work for UIs to be able to migrate seamlessly.

**Comment by djhouseknecht** [comment] 2022-05-20 19:34
@bdbvb, Garrett just put up PR #708 to get this fixed. It will go out in the next release which will probably happen next week sometime.

**Closed as completed** 2023-03-07 19:58 UTC
